### ISSUE TITLE
ERROR: freetype2 not found using pkg-config

### ISSUE THREAD

**Issue by alicera** [ubawurinna/freetype-windows-binaries#10]
Follow the [installation](https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/#compiling-for-windows) and add `--enable-libfreetype`.  
I use `--extra-cflags` and `--extra-ldflags` to assign the path of libfreetype binary.  
But meet the error  `ERROR: freetype2 not found using pkg-config` and it try to use pkg-config to find freetype2  .pc file 
```
END ./ffconf.XlJKo3ZL/test.cu
nvcc -gencode arch=compute_52,code=sm_52 -O2 -m64 -ptx -c -o ffconf.XlJKo3ZL/test.o ffconf.XlJKo3ZL/test.cu
test.cu
require_pkg_config libfreetype freetype2 ft2build.h FT_FREETYPE_H FT_Init_FreeType
check_pkg_config libfreetype freetype2 ft2build.h FT_FREETYPE_H FT_Init_FreeType
test_pkg_config libfreetype freetype2 ft2build.h FT_FREETYPE_H FT_Init_FreeType
false --exists --print-errors freetype2
ERROR: freetype2 not found using pkg-config
```

**Comment by ubawurinna** [comment]
You have to create your own .pc file and use the dll version import library.
You can't use the static version of the library with MinGW or you will have to compile a static MinGW library yourself from the freetype sources.

**Comment by alicera** [comment]
1. How to create .pc ?
2. I use [freetype-windows-binaries](https://github.com/ubawurinna/freetype-windows-binaries/releases) and build ffmpeg with `--extra-cflags="-I../freetype-windows-binaries-2.11.1/include" `   and   `--extra-ldflags="-LIBPATH:../freetype-windows-binaries-2.11.1/win64"`
So, the method is mistake ?
