### ISSUE TITLE
The library seems to be compiled without the Subpixel/Harmony rendering support

### ISSUE THREAD

**Issue by bilativ** [ubawurinna/freetype-windows-binaries#11]
FT_Library_SetLcdFilter(TFTManager.Library, ftlcdfLight) returns error code 7
FR_Load_Glyph with ftlfLCD fails with the error code 19

**Comment by ubawurinna** [comment]
This freetype distribution is compiled from unmodified source code, and the FT_CONFIG_OPTION_SUBPIXEL_RENDERING option is not set by default.

As an alternative you can use **Harmony rendering**.
Harmony rendering is equivalent to ClearType with light filter.
https://freetype.org/freetype2/docs/reference/ft2-lcd_rendering.html

If you still want to use ClearType rendering you should compile freetype from source by enabling the FT_CONFIG_OPTION_SUBPIXEL_RENDERING option.
