### ISSUE TITLE
MinGW Compiler bins?

### ISSUE THREAD

**Issue by aqilc** [ubawurinna/freetype-windows-binaries#12]
I want to compile my program with MinGW, but am unable to do so because the MSVC .lib formats are incompatible with GNU. If you could provide ones compiled with MinGW or CYGwin, that'd be amazing!!!

**Comment by apodtele** [comment]
It is not clear from your report if you use static lib or dynamic lib+dll. In the latter case, try using dll directly on the command line.

**Comment by aqilc** [comment]
I needed static libs, sorry.

**Comment by aqilc** [comment]
Is there any way you could do this? All that is needed is for you to compile Freetype using MinGW binaries hosted at https://winlibs.com/ or any other source.  VS and MinGW `.lib` (static lib) files are different and incompatible, so I think this would be appreciated.

**Comment by apodtele** [comment]
Have you seen https://packages.msys2.org/base/mingw-w64-freetype? It is a part of the [msys2](https://www.msys2.org/) distribution, which is somehow different from WinLibs. I am sure you can work with them to have a windows native build too. Of course, there is also option to build FreeType yourself with WinLibs community help.

Basically, you are asking wrong people here. You should redirect your inquiries.

**Comment by aqilc** [comment]
Ok thank you! This was just the unofficial repo for Freetype Windows Builds so I thought it would be a fit request here.

I don't really think there's a WinLibs community either, but I'll try. Thanks again for the guidance!
