### ISSUE TITLE
Using zlib and freetype static libraries causes LNK2005/LNK4006

### ISSUE THREAD

**Issue by blackandwhitebg** [ubawurinna/freetype-windows-binaries#13]
Hi,
When linking both lib files (freetype.lib and zlib.lib) from a single project, I get errors because parts of zlib are integrated in freetype.lib:

1>zlib.lib(inflate.obj) : warning LNK4006: inflateEnd already defined in freetype.lib(ftgzip.obj); second definition ignored
1>zlib.lib(inflate.obj) : warning LNK4006: inflate already defined in freetype.lib(ftgzip.obj); second definition ignored
1>zlib.lib(inflate.obj) : warning LNK4006: inflateInit2_ already defined in freetype.lib(ftgzip.obj); second definition ignored
1>zlib.lib(inflate.obj) : warning LNK4006: inflateReset2 already defined in freetype.lib(ftgzip.obj); second definition ignored
1>zlib.lib(inflate.obj) : warning LNK4006: inflateReset already defined in freetype.lib(ftgzip.obj); second definition ignored
1>zlib.lib(inflate.obj) : warning LNK4006: inflateResetKeep already defined in freetype.lib(ftgzip.obj); second definition ignored

I found a workaround, which is compiling with /FORCE:MULTIPLE.
Is there a cleaner way to solve the problem?
Thank you

**Comment by ubawurinna** [comment]
/FORCE:MULTIPLE will only hide the problem. Your application might crash unexpectedly if the wrong function is called.  
A simple way to solve the problem is to use the import library and dll in the **release dll** folder, because in this case the inflatexxx functions are not exported.

**Comment by ubawurinna** [comment]
It seems to be a bug in the freetype sources when compiling static libraries under Windows.
I modified the source and now the zlib functions are not exported anymore.  
  
@blackandwhitebg Can you try the libraries in commit 7e8053aa ?

**Comment by blackandwhitebg** [comment]
Thank you for your response.
Yes, this works. The issue can be closed.

(Since using the lib is most likely the preferred way for people who don't want any external dependencies, I would only add a suggestion for future releases to include different libs with /MT and /MD compilations, so whoever wants just a single executable, not depending on anything else at all can use the /MT compilation)
