### ISSUE TITLE
Function not found in 64-bit version

### ISSUE THREAD

**Issue by pm-docuvive** [ubawurinna/freetype-windows-binaries#2]
Hi @ubawurinna
I downloaded your Windows 64-bit binaries for use alongside [freetype-py](https://github.com/rougier/freetype-py).
At runtime I get the following error:
`function 'FT_Get_BDF_Charset_ID' not found`
From what I can gather, this appears to be due to functions not being exported correctly for 64-bit DLLs (see comment by @mdsitton 09 nov 2014 on [this thread](https://github.com/rougier/freetype-py/issues/17))
Do you happen to have any more recent 64-bit binaries that I could test?
Thanks in advance

**Comment by HinTak** [comment]
See my answer.
https://github.com/rougier/freetype-py/issues/17#issuecomment-345205940

There is perhaps nothing for you to do - I file https://github.com/rougier/freetype-py/issues/65 for possible future work in freetype-py.

**Comment by ubawurinna** [comment]
This issue was resolved in freetype **v2.9**

**Comment by HinTak** [comment]
Yes, I reported the issue upstream and the Freetype people updated the visual studio build files to include the older and unix centric font format. A later release of freetype-py also contains a work around against older Freetype binaries. In other words, updating either Freetype or Freetype-py , or both, should fix this.
