### ISSUE TITLE
freetype2-demos to add

### ISSUE THREAD

**Issue by apodtele** [ubawurinna/freetype-windows-binaries#4]
Would you compile and distribute some of [freetype2-demos](https://git.savannah.gnu.org/cgit/freetype/freetype2-demos.git/)? Perhaps not all of therm, but ftview, ftgrid, and ftdump are quite useful. I can provide my solution and project files if you are interested.

**Comment by ubawurinna** [comment]
Yes if you provide me with the visual studio projects I can compile the demos and add them to my release.

**Comment by apodtele** [comment]
I've just committed my demo projects https://gitlab.freedesktop.org/freetype/freetype-demos/-/commit/15117a3bc040626e5734e6dac5d3009dbdaec771

**Comment by ubawurinna** [comment]
Thank you for the projects.
I added the demos in the commit d4491e774f526cb0a62d08a601501c7eedf9b55b

**Comment by apodtele** [comment]
Excellent! Please let me know if you'd like to improve the projects.
