### ISSUE TITLE
Static lib version

### ISSUE THREAD

**Issue by roman-kirsanov** [ubawurinna/freetype-windows-binaries#5]
Please 🥺

**Comment by ubawurinna** [comment]
You will find them in the commit 9f192c8aa5cad26a74e2131e8856209d6d15df45
release static/win32/freetype.lib
release static/win64/freetype.lib

**Comment by roman-kirsanov** [comment]
> You will find them in the commit [9f192c8](https://github.com/ubawurinna/freetype-windows-binaries/commit/9f192c8aa5cad26a74e2131e8856209d6d15df45)
> release static/win32/freetype.lib
> release static/win64/freetype.lib

I highly appreciate it! I owe you a beer, when u come in Moscow just let me know :)
