### ISSUE TITLE
Which options are these compiled with?

### ISSUE THREAD

**Issue by albertvaka** [ubawurinna/freetype-windows-binaries#6]
Can you please update the README to include the compiler options (eg: `FT_WITH_ZLIB`, `FT_WITH_PNG`, etc.) those binary libraries are compiled with? To avoid confusion if someone expects them to be compiled in a certain way.

**Comment by ubawurinna** [comment]
Cmake is not used for compilation, the `FT_WITH_xxx` options are not used.
To know which options are used, look at the file **include\freetype\config\ftoption.h**
These are the options defined by default in the freetype source distribution (and used by the library).

**Comment by albertvaka** [comment]
So it looks like PNG support is disabled (so: no color emoji support) in these DLLs. It might be still worth noting that, but otherwise I have no other comments :) Closing this, thanks for your time!

**Comment by apodtele** [comment]
I am thinking about adding the GDI+ PNG decoder.

**Comment by albertvaka** [comment]
Did you end up adding the PNG decoder?
