### ISSUE TITLE
I hate to sound noobish...

### ISSUE THREAD

**Issue by patrikpatrik** [ubawurinna/freetype-windows-binaries#8]
But the following code says to do this:
`#include "ft2build.h"
#include FT_FREETYPE_H`

I have included the ft2build.h in the root directory as told, and I'm supposed to #include the 2nd and not #define it? I'm getting an error:

`fatal error C1083: Cannot open include file: 'freetype/config/ftheader.h': No such file or directory`

I apologize in advance if it's been asked a billion times.. I couldn't find anything on this or the links  were dead.

**Comment by ubawurinna** [comment]
In your project properties add to the include path to the freetype include folder (ie: **$(ProjectDir)\include**)
In your code add **#include <ft2build.h>**
Then add the includes you need, e..g. **#include FT_FREETYPE_H**, **#include FT_GLYPH_H**
