### ISSUE TITLE
FT_Library_Version returns version 2.10.1 for release dll\win64\freetype.dll of version 2.11.1

### ISSUE THREAD

**Issue by rootext** [ubawurinna/freetype-windows-binaries#9]
sha-256
1c487392d6d06970ba3c7b52705881f1fb069f607243499276c2f0c033c7df6f *freetype.dll

**Comment by ubawurinna** [comment]
The dll returns the correct version.
You must have an old dll somewhere on your machine that your application uses instead of the desired one.

**Comment by rootext** [comment]
Sorry, my bad
